name: build

on:
  push:
    branches:
      - main

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
  OWNER: ${{ github.repository_owner }}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@807dd8a807e8cf2a6d3e7e77fc4b74533f0cd7ae # v4.6.38
        with:
          save-cache: true

      - run: pnpm prettier

  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          show-progress: false

      - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Docker registry login
        if: env.DRY_RUN == 'false'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ env.OWNER }} --password-stdin

      - name: Publish to ghcr.io
        uses: containerbase/internal-tools@807dd8a807e8cf2a6d3e7e77fc4b74533f0cd7ae # v4.6.38
        with:
          command: docker-builder
          platforms: linux/amd64,linux/arm64
          image-prefix: ghcr.io/${{ env.OWNER }}
          major-minor: false
          dry-run: ${{ env.DRY_RUN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          show-progress: false

      - name: Init
        run: ./bin/init.sh

      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        if: env.DRY_RUN == 'false'
        with:
          allowUpdates: true
          body: See https://github.com/nodejs/node/releases/tag/v${{ env.VERSION }} for more changes
          commit: ${{ github.sha }}
          name: ${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
