name: build

on:
  push:
    branches:
      - main

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
  OWNER: ${{ github.repository_owner }}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@63eddd1e1512b0b300bd0e8c040582abdd63ae85 # v4.5.5
        with:
          save-cache: true

      - run: pnpm prettier

  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false

      - uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1

      - name: Docker registry login
        if: env.DRY_RUN == 'false'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ env.OWNER }} --password-stdin

      - name: Publish to ghcr.io
        uses: containerbase/internal-tools@63eddd1e1512b0b300bd0e8c040582abdd63ae85 # v4.5.5
        with:
          command: docker-builder
          platforms: linux/amd64,linux/arm64
          image-prefix: ghcr.io/${{ env.OWNER }}
          major-minor: false
          dry-run: ${{ env.DRY_RUN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false

      - name: Init
        run: ./bin/init.sh

      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        if: env.DRY_RUN == 'false'
        with:
          allowUpdates: true
          body: See https://github.com/nodejs/node/releases/tag/v${{ env.VERSION }} for more changes
          commit: ${{ github.sha }}
          name: ${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
